@baseUrl = http://localhost:3000

### Read all users
GET {{baseUrl}}/users

### Post a user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "John Doe",
    "password": "test"
}
